### ISSUE TITLE
Parallel Relation Extraction Dataset

### ISSUE THREAD

**Issue by nasrin-taghizadeh** [davidsbatista/Annotated-Semantic-Relationships-Datasets#2]
Hi David,
I'm working on RE. Since you collected several useful corpus, I want to know if there is any parallel corpus with semantic relations? I mean parallel corpus, with aligned entity tags and semantic label.

Thanks in advance
Best Regard
Nasrin

**Comment by davidsbatista** [comment]
nope, not that I know of.
