### ISSUE TITLE
KBP37 Dataset

### ISSUE THREAD

**Issue by sahitya0000** [davidsbatista/Annotated-Semantic-Relationships-Datasets#3]
You can add Dataset KBP37 to the list. 
https://github.com/zhangdongxu/kbp37

**Comment by davidsbatista** [comment]
thanks! can you point me to the paper that describes this dataset?

**Comment by davidsbatista** [comment]
is this the one? https://arxiv.org/pdf/1508.01006.pdf

**Comment by sahitya0000** [comment]
Yes.

**Comment by davidsbatista** [comment]
Dataset and respective paper added to Traditional Information Extraction. Thanks for the suggestion!

Best,
David
