### ISSUE TITLE
Datasets can be opened

### ISSUE THREAD

**Issue by tyj117** [davidsbatista/Annotated-Semantic-Relationships-Datasets#4]
Hi,
I downloaded the SemEval2007-Task4.tar.gz dataset, I tried to open it by using 'tar -zxvf' or 'gunzip'. However, it just showed me errors: 'Unrecognized archive format' and 'not in gzip format'.
I used 'file' to check the format, it shows 'SemEval2007-Task4.tar.gz: HTML document text, UTF-8 Unicode text, with very long lines'.
Could you tell me how to open this dataset?
Regards
Niko

**Comment by davidsbatista** [comment]
it works for me, using Mac OS X:

```
13:24 $ tar zxpvf SemEval2007-Task4.tar.gz
x SemEval2007-Task4/
x SemEval2007-Task4/._.DS_Store
x SemEval2007-Task4/.DS_Store
x SemEval2007-Task4/._key.tar.gz
x SemEval2007-Task4/key.tar.gz
x SemEval2007-Task4/._test.tar.gz
x SemEval2007-Task4/test.tar.gz
x SemEval2007-Task4/._train.tar.gz
x SemEval2007-Task4/train.tar.gz
x SemEval2007-Task4/._trial.tar.gz
x SemEval2007-Task4/trial.tar.gz
```
