### ISSUE TITLE
kbp37-master.zip crashed

### ISSUE THREAD

**Issue by andyyuan78** [davidsbatista/Annotated-Semantic-Relationships-Datasets#6]
gpuws@gpuws32g:/media/gpuws/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/Annotated-Semantic-Relationships-Datasets-1/datasets$ unzip kbp37-master.zip 
Archive:  kbp37-master.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of kbp37-master.zip or
        kbp37-master.zip.zip, and cannot find kbp37-master.zip.ZIP, period.

**Comment by davidsbatista** [comment]
`kbp37-master.zip: gzip compressed data, last modified: Fri Sep  7 08:39:55 2018, from Unix`

try to use gzip
