### ISSUE TITLE
Can you add the PGR and PGR-crowd datasets?

### ISSUE THREAD

**Issue by dpavot** [davidsbatista/Annotated-Semantic-Relationships-Datasets#8]
https://github.com/lasigeBioTM/PGR (Distant Supervision)
https://github.com/lasigeBioTM/PGR-crowd (Crowdsourcing & Distant Supervision)

**Comment by davidsbatista** [comment]
Hi @dpavot, you can add it yourself, just open a PR, with the correct description, links to papers and files or files themselves; let me know you if you need any help :)

**Comment by dpavot** [comment]
I opened a PR. I hope everything is well. Thank you for adding PGR and PGR-crowd! :)
